import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Opdracht Voertuigtechniek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center w-screen h-screen space-y-8">
        <h1 className="text-4xl">Opdracht Voertuigtechniek MRV1F 2022-2023</h1>
        <li className="list-none flex space-x-3 text-xl">
          <ul className="hover:underline cursor-pointer">
            <Link href="/opdracht-1">
              <a>Opdracht 1</a>
            </Link>
          </ul>
          <ul>|</ul>
          <ul className="hover:underline cursor-pointer">
            <Link href="/opdracht-2">
              <a>Opdracht 2</a>
            </Link>
          </ul>
        </li>
        <div></div>
      </main>
    </div>
  );
};

export default Home;
