import type { NextPage } from "next";
import Head from "next/head";

const AssignmentTwo: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Opdracht 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center w-screen h-screen space-y-8">
        <h1 className="text-4xl">Opdracht 2</h1>
        <div></div>
      </main>
    </div>
  );
};

export default AssignmentTwo;
